### PR TITLE
Minor stuff

### PR DESCRIPTION
**Pull request by romancm**
Use shorthand for input event
Make key value more specific
Kebab-case component tag
Missing semi-colon

### CODE REVIEW

**Comment by SaraVieira** [comment]
Hey!

I actually don't use semicolons, that's by design 😂

Also I do perfer when components have the first letter upercase maybe that's for coming from the react world :/

**Comment by romancm** [comment]
Ah my bad, updated to match your style.

**Comment by SaraVieira** [comment]
Oh! Awesome! Thank you so much!

@all-contributors please add @romancmx for code

**Comment by SaraVieira** [comment]
@all-contributors please add @romancmx for code

**Comment by SaraVieira** [comment]
Merged ! :D

**Pull request merged**
